version: "3.9"

services:
  nginx:
    image: nginx:latest
    container_name: nginx_server
    ports:
      - "80:80"    # Puerto host : puerto contenedor
    volumes:
      - ./nginx/conf:/etc/nginx/conf.d  # tus configuraciones personalizadas
      - ./nginx/html:/usr/share/nginx/html  # tus archivos web
    restart: unless-stopped